name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: myimage:latest
        outputs: type=docker,dest=/tmp/sepp_myimage.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: sepp_myimage
        path: /tmp/sepp_myimage.tar
